version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.02.1
    steps:
      - checkout:
          path: security_access_groups
      - run:
          name: Grab REDCap Source
          command: |
            git clone --branch v13.1.27_zip https://github.com/AndrewPoppe/redcap_source
      - run:
          name: Build the REDCap Image
          command: |
            git clone https://github.com/123andy/redcap-docker-compose
            cd redcap-docker-compose/rdc
            sed 's|\(DOCKER_PREFIX\)=.*|\1=rc13_php7.4|' .env-example |
            sed 's|\(TZ\)=.*|\1=America/New_York|' |
            sed 's|\(WEB_PORT\)=.*|\1=13740|' |
            sed 's|\(MYSQL_PORT\)=.*|\1=13746|' |
            sed 's|\(PHPMYADMIN_PORT\)=.*|\1=13741|' |
            sed 's|\(MAILHOG_PORT\)=.*|\1=13745|' > .env
      - run:
          name: Start Docker REDCap Container
          working_directory: ./redcap-docker-compose/rdc
          command: docker-compose up -d
      - run:
          name: Move REDCap Source File
          command: mv redcap_source/redcap13.1.27.zip security_access_groups/tests/playwright/setup/
      - run:
          name: Install dependencies
          working_directory: ./security_access_groups/tests/playwright
          command: npm install
      - run:
          name: Install Playwright
          working-directory: ./security_access_groups/tests/playwright
          command: npx playwright install --with-deps
      - run:
          name: Initialize REDCap
          working_directory: ./security_access_groups/tests/playwright/setup
          command: node installREDCap.js
      - store_artifacts:
          path: ./security_access_groups/tests/playwright/setup/screenshots
          destination: setup
      - run:
          name: Move module files
          command: |
            sudo chmod -R 777 ./redcap-docker-compose/www/modules
            mv ./security_access_groups ./redcap-docker-compose/www/modules/security_access_groups_v99
      - run:
          name: Run Playwright Tests
          working_directory: ./redcap-docker-compose/www/modules/security_access_groups_v99/tests/playwright
          command: npx playwright test
      - store_artifacts:
          destination: test-results
          path: ./redcap-docker-compose/www/modules/security_access_groups_v99/tests/playwright/test-results/
      - store_artifacts:
          destination: playwright-report
          path: ./redcap-docker-compose/www/modules/security_access_groups_v99/tests/playwright/playwright-report/
          
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: REDCap Tests