version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.02.1
    parallelism: 8
    steps:
      #- checkout
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get update
            sudo apt-get install mysql-client-core-8.0
      - run:
          name: Build the REDCap Image
          command: |
            git clone --branch v11.1.29 https://github.com/aldefouw/redcap_docker
      - run:
          name: Get REDCap Source
          command: |
            git clone --branch v13.1.27 https://github.com/AndrewPoppe/redcap_source www
      - run:
          name: Start Docker REDCap Container
          command: |
            cd /home/circleci/project/redcap_docker
            docker-compose up -d
      - run:
          name: Change eDocs folder permissions
          command: |
            sudo chmod 777 /var/edocs
      - run:
          name: Install module
          command: |
            cd /home/circleci/project/www/modules
            git clone "$CIRCLE_REPOSITORY_URL" security_access_groups_v99
      - run:
          name: Install Playwright
          command: |
            cd /home/circleci/project/www/modules/security_access_groups_v99/tests/playwright
            npx playwright install-deps chromium
      - run:
          name: Run Tests
          command: |
            npx playwright test
      - store_artifacts:
          path: /home/circleci/project/www/modules/security_access_groups_v99/tests/playwright/test-results
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: REDCap Tests